# Generated by Django 4.2.7 on 2023-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveBigIntegerField()),
                ('sex', models.PositiveBigIntegerField()),
                ('a1', models.PositiveIntegerField()),
                ('a2', models.PositiveIntegerField()),
                ('a3', models.PositiveIntegerField()),
                ('a4', models.PositiveIntegerField()),
                ('a5', models.PositiveIntegerField()),
                ('a6', models.PositiveIntegerField()),
                ('a7', models.PositiveIntegerField()),
                ('a8', models.PositiveIntegerField()),
                ('a9', models.PositiveIntegerField()),
                ('a10', models.PositiveIntegerField()),
                ('jaundice', models.PositiveIntegerField()),
                ('asd_history', models.PositiveIntegerField()),
                ('test_completed_by', models.PositiveIntegerField()),
                ('outcome', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
